### ISSUE TITLE
Just a thanks :)

### ISSUE THREAD

**Issue by marksev1** [videgro/Ships#1]
Just wanted to let you know, thanks for the app. I will probably test it in a few months because now its winter here and I'm not planning to go to the seaside, but I like the concept of it! Maybe it would be cool if you also explained on the blog the steps on how to connect OpenCPN to your app.

**Comment by videgro** [comment]
Thank you.
 
To connect this Android application to **OpenCPN** you need to have a computer which is running OpenCPN, [learn here how to prepare the OpenCPN client computer](http://blog.videgro.net/2015/12/raspberry-pi-automatic-identification-system-ais-receiver/#prepare_client_computer) (Prepare client computer). 

Next you have to change in the Settings of the Android Ships application: 'AIS Messages destination host'. Type here the IP address of the computer which is running OpenCPN. 

Unfortunately it is at the moment not possible to stop the receiver in a correct way and use the new setting. So you have to restart the Ships-application the hard way:
1. Press HOME
2. Remove DVB-T-DAB-FM receiver
3. Insert DVB-T-DAB-FM receiver
4. Start Ships

[Learn here how to define in OpenCPN a connection where Android Ship can send it's NMEA messages](http://blog.videgro.net/2015/12/raspberry-pi-automatic-identification-system-ais-receiver/#start_ais_nmea_client) (Start AIS/NMEA client).

As a **bonus** you can repeat the by OpenCPN received NMEA messages back to Android: Create a second connection in OpenCPN, use as IP address the address of your Android device and don't select 'Receive Input on this Port' but select 'Output on this port'. Now the ships will be displayed both in OpenCPN and in the Android Ships application.

**Comment by marksev1** [comment]
Could you make this connection between android ship and opencpn also via bluetooth? Because for example "on the go" i think that would be the most simple solution. So that it sent NMEA AIS messages to OpenCPN on the laptop/tablet via bluetooth.
