### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Jervelund** [videgro/Ships#2]
I have a really poor RTL SDR (ppm is -334), so I can't use the compiled version on Google Play - inputting the ppm value manually doesn't work, as it's outside the allowed boundaries. Therefore I wanted to compile my own, but it seems that the specific versions of rtl-sdr and rtl-ais aren't available (anymore?).

The newest version of [rtl-sdr](https://github.com/keenerd/rtl-sdr) doesn't contain rtl-sdr-android.c, which is listed in CMakeLists.txt.

Can you share the specific version you have of those libraries?
(Alternatively, compile with ppm limits -1000/1000 and push that version to Google Play)

Thanks in advance

**Comment by videgro** [comment]
Dear Sigurd, I just published a new version of the app to Google Play (version 3.00), which has a PPM range from -1000 to 1000. Hope this helps you.
