### ISSUE TITLE
gradle sync issues

### ISSUE THREAD

**Issue by abdazzamajhari** [videgro/Ships#3]
i've got error on windows 10, Android Studio 3.5

ERROR: Cause: executing external native build for cmake D:\Android\Ships-master\app\src\main\jni\CMakeLists.txt

**Comment by abdazzamajhari** [comment]
still cant, migrate doesnt works to

**Comment by videgro** [comment]
It is not possible to build a working product from this GIT repo (as intended). You can find a compiled version at Google Play store: https://play.google.com/store/apps/details?id=net.videgro.ships
