### ISSUE TITLE
cant turn off cloud input source

### ISSUE THREAD

**Issue by kirk276** [videgro/Ships#5]
My receiver is working fine for local area, but i'm getting a flood of inputs from an area in China, I'm located in Greece. all the inputs the source is listed as cloud. but in the settings the "repeat from cloud" in not checked. in fact i have all boxes under the repeter settings un-checked. all vessels appear to be in same general area, 32 lat 118 long. first few days i used the app I didn't have this issue, it started today. let me know if you require more info. since I only installed this 4 days ago i'm assuming i'm running the latest version.

**Comment by videgro** [comment]
You can turn off the vessels from the cloud by pressing the + icon at the map and uncheck: "Ships - Peers"  and "Ship traces - Peers". See also video: https://youtu.be/NEf3cfDKDe0?t=109

**Comment by kirk276** [comment]
maybe that's the problem, when i press the + icon nothing happens, not even the click sound that indicates you touched something clickable, like when i touch the ship icon or the i icon at the bottom.
